name: run sync_openalex_affiliations_github_issues.py

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 8 AM

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run python script # run sync_openalex_affiliations_github_issues.py
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          ODS_API_KEY: ${{ secrets.ODS_API_KEY }}
        run: python sync_openalex_affiliations_github_issues.py
 